import type { Metadata } from "next";
import "./globals.css";
import TetrisBackground from '../components/TetrisBackground';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'system-ui, sans-serif', position: 'relative' }}>
        <TetrisBackground />
        {children}
      </body>
    </html>
  );
}
